# App.yaml file

# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python39
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "settings"
  DB_NAME: "db_name"
  DB_USERNAME: "db_user"
  DB_PASSWORD: "db_password"
  DB_HOST: "/cloudsql/detector-db:us-centrial1:senators"
  DB_PORT: 3306
  DB_TIMEOUT: 5000

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.

- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto