version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  web:
    image: radbydesign/django-api:v0.5
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000 && python manage.py migrate'
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  vue:
    image: radbydesign/vue:v0.3
    volumes:
      - './frontend/:/usr/src/app'
      - '/app/node_modules'
    command: "sh -c 'yarn serve'"
    ports:
      - '8081:8080'
