# Generated by Django 2.1.14 on 2021-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senator',
            options={},
        ),
        migrations.RemoveField(
            model_name='senator',
            name='code',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='created',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='language',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='style',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='title',
        ),
        migrations.AddField(
            model_name='senator',
            name='first_name',
            field=models.CharField(default='First Name', max_length=200),
        ),
        migrations.AddField(
            model_name='senator',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=200),
        ),
        migrations.AddField(
            model_name='senator',
            name='short_title',
            field=models.CharField(default='Senator', max_length=200),
        ),
    ]
