# .github/workflows/deploy

# https://cloud.google.com/python/django/appengine
# https://github.com/actions-hub/gcloud:


name: deploy-app-to-gcp

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_PROD_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_GITHUB_CREDENTIALS}}
        with:
          args: app deploy ./app.yaml
